name: calvin-act
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pandas
  - pyarrow
  - tqdm
  - ffmpeg
  - pip:
      - huggingface_hub
      - wandb
      - jsonlines
      - safetensors
      - -e .
